markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jemoji
exclude: [bin, vendor, "Gemfile", "Gemfile.lock", "README.md"]
url: https://mikeknep.com
author: Mike Knepper
title: Invisible Cities
collections:
  notes:
    output: true
